baseURL = "https://alex.guinman.id.au/"
title = "Alex Guinman"
subtitle = "Personal blog of Alex Guinman"
languageCode = "en-gb"
paginate = 10
theme = "mainroad"
timeout = 60000

[Author] # Used in authorbox
  name = "Alex Guinman"
  avatar = "https://en.gravatar.com/userimage/18263558/00c0940b182d75a62218fe91404f6bc0.jpg?size=400"
  
[Params]
  description = "Personal blog of Alex Guinman"
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true  
  toc = true # Enable Table of Contents
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "taglist"]

[Params.widgets.social]
  # Enable parts of social widget
  github = "aguinane"

[permalinks]
  posts = "posts/:year/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  

[[menu.main]]
    name = "Travel"
    identifier = "travel"
    url = "/categories/travel/"

[[menu.main]]
    name = "Misc"
    identifier = "misc"
    url = "/categories/misc/"
    
[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/pages/about/"      
  
