# The URL the site will be built for
base_url = "https://alex.guinman.id.au"
title = "Alex Guinman"
description = "Personal blog"

# The default author for pages
author = "Alex Guinman"

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# RSS Feed
generate_feeds = true
feed_filenames = ["atom.xml", 'rss.xml']
feed_limit = 40

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
    { name = "series", feed = true },
]

[markdown]
highlight_code = true
lazy_async_image = true

[extra]
# Put all your custom variables here
date_format = "%Y-%m-%d"
email = "jane@doe.com"
name = "Alex Guinman"
images_default_size = 1200
images_sizes = [100, 200, 400, 800, 1200, 1600, 2400, 3200]
images_sizes_attr = "auto, (min-width: 800px) 800px, 100vw"
