baseURL = "https://alex.guinman.id.au/"
languageCode = "en-gb"
title = "Alex Guinman"
subtitle = "Personal blog of Alex Guinman"
theme = "hugo-theme-stack"
paginate = 9

[outputs]
  home = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe= true

[params]
  author = "Alex Guinman"
  description = "Personal blog of Alex Guinman"
  favicon = ""
  themeColor = "theme-base-08"
  layoutReverse = true
  relatedPosts = true
  featuredImageField = "featured_image"

[params.sidebar.avatar]
  local = false
  src = 'https://en.gravatar.com/userimage/18263558/00c0940b182d75a62218fe91404f6bc0.jpg?size=400'

[params.widget]
  enabled = ['search', 'archives', 'tag-cloud']

[params.imageProcessing.cover]
  enabled = true

[params.imageProcessing.content]
  enabled = true

[permalinks]
  posts = "posts/:year/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[menu.main]]
    name = "Travel"
    identifier = "travel"
    url = "/categories/travel/"

[[menu.main]]
    name = "Misc"
    identifier = "misc"
    url = "/categories/misc/"
    
[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/pages/about/"    
